name: Bounties
version: '${project.version}'
main: com.semivanilla.bounties.Bounties
api-version: 1.18
softdepend: [ SquaremapPlayers, PlaceholderAPI ]
authors: [ Alen_Alex ]
description: A Custom Plugin Developed By Semi-Vanilla MC For Player Head Bounties And Square Map Integration
